### PR TITLE
Added (useless) gamma function for calculating positive real factorials

### PR DESCRIPTION
**Pull request by Shiimoe**
send feet pics

### CODE REVIEW

**Comment by Demonstrandum** [comment]
Don't like the hard coded values, at least create a #define for it, and `gamma_func` is misleading, it's not the Gamma function, but an integrand, perhaps rename it as such.

**Comment by Shiimoe** [comment]
you dumb cunt, I ASKED you whether I should do that or not and you said yes fuck you merge it

**Comment by Shiimoe** [comment]
I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you I hate you 






send feet pics

**Comment by Demonstrandum** [comment]
You know, you don't have to define a hard coded value for gamma_h, it can be calculated from the prior.  Please do that instead, so in the future, you only have to change one value, instead of calculating the new value manually.

**Comment by Shiimoe** [comment]
I am going to murder you

**Comment by Shiimoe** [comment]
MERGE THE FUCKING BRANCH

**Pull request merged**
